dist: focal
language: php

php:
  - 8.0

# Make sure we have a recent version of docker-compose.
addons:
  apt:
    packages:
      - docker-compose

before_script:
  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Install the AWS CLI and login to the ECR. Credentials are secrets set via the UI.
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
  - aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin public.ecr.aws/unocha

script:
  # Get docker information.
  - docker version
  - docker-compose version

  # PHP linting
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l

  # Build local image.
  - make

  # Create the site, redis and mysql containers.
  - docker-compose -p response-test -f tests/docker-compose.yml up -d

  # Dump some information about the created containers.
  - docker ps -a

  # Wait a bit for everything to be ready.
  - sleep 10

  # Install the dev dependencies.
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal composer install

  # Ensure the drupal coding standards config is installed.
  # - docker exec -it -u appuser -w /srv/www response-test-site ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer

  # Check coding standards.
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal ./vendor/bin/phpcs -p --report=full ./html/modules/custom ./html/themes/custom

  # Run unit tests.
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal mkdir -p /srv/www/html/sites/default/files/browser_output
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -e BROWSERTEST_OUTPUT_DIRECTORY=/srv/www/html/sites/default/files/browser_output -T drupal ./vendor/bin/phpunit --testsuite Unit --debug

  # Install the site with the existing config.
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal drush -y si --existing-config
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal drush -y en dblog

  # Ensure the file directories are writable.
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal chmod -R 777 /srv/www/html/sites/default/files /srv/www/html/sites/default/private

  # Create the build logs directory and make sure it's writable.
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal mkdir -p /srv/www/html/build/logs
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -T drupal chmod -R 777 /srv/www/html/build/logs

  # Run all tests and generate coverage report.
  - docker-compose -p response-test -f tests/docker-compose.yml exec -w /srv/www -e XDEBUG_MODE=coverage -e BROWSERTEST_OUTPUT_DIRECTORY=/srv/www/html/sites/default/files/browser_output -e DTT_BASE_URL=http://127.0.0.1 -T drupal ./vendor/bin/phpunit --coverage-clover /srv/www/html/build/logs/clover.xml --debug

after_success:
  - echo "The tests completed without errors."
  # Create directory for clover.
  - mkdir -p ./build/logs
  - chmod -R 777 ./build/logs
  - docker cp response-test-site:/srv/www/html/build/logs/clover.xml ./build/logs/
  # Fix source files path.
  - sed -i 's#/srv/www#.#g' build/logs/clover.xml
  # Get coveralls and execute.
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - ./php-coveralls.phar -vv

after_failure:
  - echo "The tests failed. Please check the output above for problems."
  - docker-compose -p response-test -f tests/docker-compose.yml exec -T drupal drush watchdog:show --count=50 --extended
