display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        node_bulk_form:
          label: 'Formulaire des opérations en masse sur les nœuds'
          action_title: Action
        title:
          label: Titre
          separator: ', '
        type:
          label: 'Type de contenu'
          separator: ', '
        name:
          separator: ', '
        operations:
          label: Actions
      filters:
        status:
          expose:
            label: 'Statut de publication'
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: Publié
              2:
                title: 'Non publié'
        type:
          expose:
            label: 'Type de contenu'
        title:
          expose:
            label: Titre
  page_1:
    display_title: Page
