display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        entity_field:
          label: 'Champs entité'
          separator: ', '
        entity_langcode:
          label: "Langue de l'entité"
          separator: ', '
        url:
          label: URL
          separator: ', '
        last_check:
          label: 'Vérifié pour la dernière fois'
          separator: ', '
        method:
          label: Méthode
          separator: ', '
        code:
          label: 'Code du statut'
          separator: ', '
        error:
          label: Erreur
          separator: ', '
        fail_count:
          separator: ', '
        status:
          separator: ', '
        operations:
          label: Actions
      filters:
        url:
          expose:
            label: URL
        code_1:
          expose:
            label: 'Code du statut'
          group_info:
            label: Résultat
        code:
          expose:
            label: 'Code du statut'
        entity_langcode:
          expose:
            label: "Langue de l'entité"
      footer:
        result:
          content: 'Affichage de @start à @end sur @total'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: 'Liens brisés'
