_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_denied: 0
  amazon_ses: 0
  aws: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor5: 0
  components: 0
  config: 0
  config_split: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  dashboards: 0
  date_recur: 0
  datetime: 0
  datetime_range: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  env_link_fixer: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  externalauth: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  flexible_permissions: 0
  fullcalendar_api: 0
  geofield: 0
  gnode: 0
  group: 0
  gtm_barebones: 0
  help: 0
  hr_analytics: 0
  hr_entity_freshness: 0
  hr_mailchimp: 0
  hr_paragraphs: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_webp: 0
  imageapi_optimize_webp_responsive: 0
  imagemagick: 0
  jquery_ui: 0
  jquery_ui_button: 0
  jquery_ui_checkboxradio: 0
  jquery_ui_controlgroup: 0
  jquery_ui_dialog: 0
  jquery_ui_draggable: 0
  jquery_ui_resizable: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  link_allowed_hosts: 0
  linkchecker: 0
  locale: 0
  mailsystem: 0
  maintenance200: 0
  masquerade: 0
  memcache: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_views: 0
  monitoring: 0
  mysql: 0
  node: 0
  ocha_azure_tweaks: 0
  ocha_monitoring: 0
  ocha_search: 0
  openid_connect: 0
  openid_connect_windows_aad: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  paragraphs_admin: 0
  paragraphs_group_permissions: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  rest: 0
  seckit: 0
  select2: 0
  serialization: 0
  shortcut: 0
  social_api: 0
  social_auth: 0
  sophron: 0
  subgroup: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  theme_switcher: 0
  token: 0
  token_or: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  username_enumeration_prevention: 0
  variationcache: 0
  views_data_export: 0
  views_field_compare: 0
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  common_design: 0
  common_design_subtheme: 0
  claro: 0
profile: minimal
