_core:
  default_config_hash: ZT0ACgdXm4m65rwBVtAR0TGxX6QsMptRkbldivu-7yI
client_id: REPLACE_ME
client_secret: REPLACE_ME
base_url: 'https://auth.humanitarian.id'
auto_redirect: true
disable_default: true
disable_password_fields: true
disable_email_field: true
disable_user_field: true
